// <auto-generated />
namespace IssueLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addpasswordfieldtoUsertable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpasswordfieldtoUsertable2));
        
        string IMigrationMetadata.Id
        {
            get { return "201902161659066_add password field to User table 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
